### PR TITLE
Fix header attribute validated in the body

### LINKED ISSUE #2009: Payload combining required header and body field validates incorrectly
Using the following design: "$GOPATH/src/foo/design/api.go"
```
package design

import (
	. "goa.design/goa/dsl"
)

var _ = Service("Something", func() {
	Error("bad_request")

	HTTP(func() {
		Path("/foo")
	})

	Method("create", func() {
		Payload(CreatePayload)
		Result(Foo)

		HTTP(func() {
			POST("/")
			Header("api_version:Api-Version")
			Response(StatusOK)
		})
	})

	Method("hide", func() {
		Payload(func() {
			Extend(CommonAttributes)
			Attribute("name", String)
			Attribute("user_id", Int)
			Required("api_version", "name", "user_id")
		})
		Result(Empty)
		Error("not_found")

		HTTP(func() {
			POST("/{name}/hide")
			Header("api_version:Api-Version")
			Response(StatusOK)
			Response("not_found", StatusNotFound)
		})
	})
})

var CommonAttributes = Type("Common", func() {
	Attribute("api_version", String, func() {
		Enum("1.0")
	})
})

var CreatePayload = Type("CreatePayload", func() {
	Extend(CommonAttributes)
	Attribute("name", String)
	Required("api_version", "name")
})

var Foo = ResultType("application/vnd.something.foo", func() {
	TypeName("Foo")

	Attributes(func() {
		Attribute("name", String)
		Required("name")
	})

	View("default", func() {
		Attribute("name")
	})
})
```
The validation for the "hide" action code-generates such that it always fails validation:
```
// ValidateHideRequestBody runs the validations defined on HideRequestBody
func ValidateHideRequestBody(body *HideRequestBody) (err error) {
	if body.UserID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("user_id", "body"))
	}
	if body.APIVersion != nil {
		if !(*body.APIVersion == "1.0") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("body.api_version", *body.APIVersion, []interface{}{"1.0"}))
		}
	}
	return
}
```
This is because the "API-Version" header is supposed to be checked after body validation, which it is in the generated DecodeHideRequest() method. It is incorrect to check it in body validation since it is a header. Note that ValidateCreateRequestBody() is correct, apparently because the CreatePayload is formally declared. If I change to use a formally declared HidePayload then it also code generates correctly:
```
		Payload(HidePayload)
...
var HidePayload = Type("HidePayload", func() {
	Extend(CommonAttributes)
	Attribute("name", String)
	Attribute("user_id", Int)
	Required("api_version", "name", "user_id")
})
...

// ValidateHideRequestBody runs the validations defined on HideRequestBody
func ValidateHideRequestBody(body *HideRequestBody) (err error) {
	if body.UserID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("user_id", "body"))
	}
	return
}
```

### PR DESCRIPTION
**Pull request by nitinmohan87**
Fixes #2009

### CODE REVIEW

File: expr/http_endpoint.go [hunk 1]
```diff
@@ -525,9 +525,18 @@ func (e *HTTPEndpointExpr) Finalize() {
 	init(e.Params)
 	init(e.Headers)
 
-	e.Body = httpRequestBody(e)
```
Comment (raphael) [inline expr/http_endpoint.go]: Couldn't the below just be:
```go
e.Body = httpRequestBody(e)
if e.Body != nil {
   e.Body.Finalize()
}
```
(+comments)
