### PR TITLE
Various fixes

### LINKED ISSUE #1734: Dependent result type code generation fails
image
image

```package design

import . "goa.design/goa/http/design"
import . "goa.design/goa/http/dsl"

var _ = API("cellar", func() {
	Title("Cellar Service")
	Description("HTTP service for managing your wine cellar")
	Server("http://localhost:8080")
})

var StoredBottle = ResultType("application/vnd.cellar.stored-bottle", func() {
	Description("A StoredBottle describes a bottle retrieved by the storage service.")
	Reference(Bottle)
	TypeName("StoredBottle")

	Attributes(func() {
		Attribute("id", String, "ID is the unique id of the bottle.", func() {
			Example("123abc")
		})
		Attribute("name")
		//Attribute("winery")
		Attribute("winerys", MapOf(String, Winery))
		Attribute("vintage")
		Attribute("composition")
		Attribute("description")
		Attribute("rating")

	})

	View("default", func() {
		Attribute("id")
		Attribute("name")
		Attribute("winerys", func() {
			View("tiny")
		})
		Attribute("vintage")
		Attribute("composition")
		Attribute("description")
		Attribute("rating")
	})

	View("tiny", func() {
		Attribute("id")
		Attribute("name")
		Attribute("winerys", func() {
			View("tiny")
		})
	})

	Required("id", "name", "vintage")
})

var Bottle = Type("Bottle", func() {
	Description("Bottle describes a bottle of wine to be stored.")
	Attribute("name", String, "Name of bottle", func() {
		MaxLength(100)
		Example("Blue's Cuvee")
	})
	Attribute("winery", Winery, "Winery that produces wine")
	Attribute("vintage", UInt32, "Vintage of bottle", func() {
		Minimum(1900)
		Maximum(2020)
	})
	Attribute("composition", ArrayOf(Component), "Composition is the list of grape varietals and associated percentage.")
	Attribute("description", String, "Description of bottle", func() {
		MaxLength(2000)
		Example("Red wine blend with an emphasis on the Cabernet Franc grape and including other Bordeaux grape varietals and some Syrah")
	})
	Attribute("rating", UInt32, "Rating of bottle from 1 (worst) to 5 (best)", func() {
		Minimum(1)
		Maximum(5)
	})
	Required("name", "winery", "vintage")
})

var Winery = ResultType("Winery", func() {
	Attributes(func() {
		Attribute("name", String, "Name of winery", func() {
			Example("Longoria")
		})
		Attribute("region", String, "Region of winery", func() {
			Pattern(`(?i)[a-z '\.]+`)
			Example("Central Coast, California")
		})
		Attribute("country", String, "Country of winery", func() {
			Pattern(`(?i)[a-z '\.]+`)
			Example("USA")
		})
		Attribute("url", String, "Winery website URL", func() {
			Pattern(`(?i)^(https?|ftp)://[^\s/$.?#].[^\s]*$`)
			Example("http://www.longoriawine.com/")
		})
	})
	View("default", func() {
		Attribute("name")
		Attribute("region")
		Attribute("country")
		Attribute("url")
	})
	View("tiny", func() {
		Attribute("name")
	})
	Required("name", "region", "country")
})

var Component = Type("Component", func() {
	Attribute("varietal", String, "Grape varietal", func() {
		Pattern(`[A-Za-z' ]+`)
		MaxLength(100)
		Example("Syrah")
	})
	Attribute("percentage", UInt32, "Percentage of varietal in wine", func() {
		Minimum(1)
		Maximum(100)
	})
	Required("varietal")
})

var NotFound = Type("NotFound", func() {
	Description("NotFound is the type returned when attempting to show or delete a bottle that does not exist.")
	Attribute("message", String, "Message of error", func() {
		Metadata("struct:error:name")
		Example("bottle 1 not found")
	})
	Attribute("id", String, "ID of missing bottle")
	Required("message", "id")
})

var Criteria = Type("Criteria", func() {
	Description("Criteria described a set of criteria used to pick a bottle. All criteria are optional, at least one must be provided.")
	Attribute("name", String, "Name of bottle to pick", func() {
		Example("Blue's Cuvee")
	})
	Attribute("varietal", ArrayOf(String), "Varietals in preference order", func() {
		Example([]string{"pinot noir", "merlot", "cabernet franc"})
	})
	Attribute("winery", String, "Winery of bottle to pick", func() {
		Example("longoria")
	})
})
```

### PR DESCRIPTION
**Pull request by nitinmohan87**
* Fixes a case where required attributes may not be in a view.
* In HTTP client response decode, marshal response body if method uses a viewed result type so that the transformation code checks for nil before calling the helpers.
* Fix a bug when validating security scheme in method when payload is nil
* Remove suffix "Default" from validation and init functions. (Fixes #1734)

### CODE REVIEW

File: codegen/service/service_data.go [hunk 1]
```diff
@@ -203,53 +206,63 @@ type (
...
-	// type, then a viewed result type is generated which holds the projected
-	// type and a view attribute holding the view name. Finally, the generated
-	// code also defines functions that convert the result types to and from the
-	// corresponding viewed result type as well as project the viewed result
-	// type based on a view.
-	ProjectedTypeData struct {
-		// This holds the projected type or the viewed result type.
+	// ViewedResultTypeData contains the data used to generate a viewed result type
+	// (i.e. a method result type with more than one view). The viewed result
+	// type holds the projected type and a view based on which it projects the
```
Comment (raphael) [inline codegen/service/service_data.go]: creates

File: codegen/service/service_data.go [hunk 2]
```diff
@@ -203,53 +206,63 @@ type (
...
 		// Description is the view description.
 		Description string
-		// Project is the code to project a result type based on a view.
-		Project *InitData
-		// Validate is the validation code run on the projected type.
-		Validate *ValidateData
+	}
+
+	// ProjectedTypeData contains the data used to generate a user type that can
+	// be projected based on a view. The generated type uses pointers for all
```
Comment (raphael) [inline codegen/service/service_data.go]: specify that this applies when some of the attributes are result types

File: codegen/service/service_data.go [hunk 3]
```diff
@@ -203,53 +206,63 @@ type (
...
+	// fields so that view specific validation logic may be implemented.
+	// A projected type is generated for every user type found in a viewed result
+	// type. It also contains to data to generate view-based validation logic
```
Comment (raphael) [inline codegen/service/service_data.go]: the data / clean-up repetition

File: codegen/service/service_data.go [hunk 4]
```diff
@@ -203,53 +206,63 @@ type (
...
+	// and transformation functions to convert a projected type to its
+	// corresponding service type and vice versa.
+	ProjectedTypeData struct {
+		// the projected type
+		*UserTypeData
+		// Validations lists the validation functions to run on the projected type
```
Comment (raphael) [inline codegen/service/service_data.go]: Explain what the elements of slice correspond to.

File: codegen/service/service_data.go [hunk 5]
```diff
@@ -718,52 +735,31 @@ func requirements(m *design.MethodExpr) []*design.SecurityExpr {
...
-		// If the attribute type has already been projected (i.e., projected type
-		// or a viewed result type has been generated) and if the type corresponds
-		// to a viewed result type, we change the type name to refer to a projected
-		// type instead.
-		if pd, ok := seen[pt.Name()]; ok && (pd == nil || !pd.IsViewedResult) {
-			// Projected type has already been seen and is not a viewed result type.
-			// Break the recursion.
+		dt := att.Type.(design.UserType)
+		if pd, ok := seen[dt.Name()]; ok {
+			if pd != nil {
```
Comment (raphael) [inline codegen/service/service_data.go]: Looks suspicious

File: codegen/service/service_data.go [hunk 6]
```diff
@@ -934,182 +1027,152 @@ func buildProjectData(projected, att *design.AttributeExpr, scope *codegen.NameS
...
+			Description: fmt.Sprintf("%s runs the validations defined on %s", name, tname),
+			Ref:         ref,
+			Validate:    codegen.RecursiveValidationCode(projected, false, true, false, "result"),
+		})
 	}
+	return validations
 }
 
-func buildConstructorCode(src, tgt *design.AttributeExpr, srcvar, tgtvar, srcpkg, tgtpkg string, view string, scope *codegen.NameScope, viewed bool) (string, []*codegen.TransformFunctionData) {
+func buildConstructorCode(src, tgt *design.AttributeExpr, srcvar, tgtvar, srcpkg, tgtpkg string, view string, scope *codegen.NameScope, unmarshal bool) (string, []*codegen.TransformFunctionData) {
```
Comment (raphael) [inline codegen/service/service_data.go]: Add comment, define all arguments

File: codegen/service/testdata/endpoint_code.go [hunk 7]
```diff
@@ -133,14 +133,9 @@ func NewAEndpoint(s Service) goa.Endpoint {
...
 		}
-		var vres *withresultmultipleviewsviews.Viewtype
-		switch view {
-		case "default", "":
-			vres = NewViewtypeDefault(res)
-		case "tiny":
-			vres = NewViewtypeTiny(res)
-		default:
-			return nil, fmt.Errorf("unknown view %q", view)
+		vres := NewViewedViewtype(res, view)
```
Comment (raphael) [inline codegen/service/testdata/endpoint_code.go]: Make `NewViewedViewtype` private if possible

File: http/codegen/service_data.go [hunk 8]
```diff
@@ -1253,7 +1253,7 @@ func buildResponseResultInit(resp *httpdesign.HTTPResponseExpr, e *httpdesign.En
 			Validate: vcode,
 		}}
 		var helpers []*codegen.TransformFunctionData
-		code, helpers, err = codegen.GoTypeTransform(resp.Body.Type, respBody.Type, "body", "v", "", pkg, true, svc.Scope)
+		code, helpers, err = codegen.GoTypeTransform(resp.Body.Type, respBody.Type, "body", "v", "", pkg, md.ViewedResult == nil, svc.Scope)
```
Comment (raphael) [inline http/codegen/service_data.go]: Explain why marshal vs unmarshal
