### PR TITLE
Fixes streaming endpoints with no payload

### LINKED ISSUE #2242: v3: Streaming method without payload does generate incorrect server code
Simple design:
```
package design

import . "goa.design/goa/v3/dsl"

var _ = API("api", func() {
	Server("apisvr", func() {
		Host("default", func() {
			URI("http://0.0.0.0:8000")
			URI("grpc://0.0.0.0:8080")
		})
	})
})

var _ = Service("ws", func() {
	HTTP(func() {
		Path("/")
	})

	Method("Retrieve", func() {
		StreamingResult(String)

		HTTP(func() {
			GET("/")
			Response(StatusOK)
		})
	})
})
```
The method `Retrieve` has no `Payload` defined which leads to the following error on running:
```
gen/http/ws/server/server.go:155:6: undefined: err
gen/http/ws/server/server.go:157:6: undefined: err
gen/http/ws/server/server.go:158:16: undefined: err
gen/http/ws/server/server.go:161:34: undefined: err
```
The line defining the `err` variable comes from `payload, err := decodeRequest(r)` which is missing without the payload and `err` is never declared.

### PR DESCRIPTION
**Pull request by cubic3d**
Fixes #2242. This declares the error variable outside of the payload generating section to avoid missing declaration on streaming endpoints without payload.

### CODE REVIEW

**Comment by raphael** [comment]
Thank you for opening the issue and for the PR! Here is an [example](https://github.com/goadesign/goa/commit/918b85c89cee6ed405f68eb71df145773aa7e579) on how to fix the build (see how the import statements should be formatted). This must be a recent change with `golint`, updating your copy should help reproduce the issue.

File: http/codegen/server.go [hunk 1]
```diff
@@ -454,8 +454,10 @@ func {{ .HandlerInit }}(
 		ctx = context.WithValue(ctx, goa.MethodKey, {{ printf "%q" .Method.Name }})
 		ctx = context.WithValue(ctx, goa.ServiceKey, {{ printf "%q" .ServiceName }})
 
+		var err error
```
Comment (raphael) [inline http/codegen/server.go]: Nitpick but I'm wondering if changing the code so that the `err` variable only gets defined that way in the case that there is no payload wouldn't be better so the change would be:
```go
{{- if .Payload.Ref }}
		payload, err := decodeRequest(r)
		...
- {{- end }}
+ {{- else }}
+    var err error
+ {{- end }}
```

Comment (cubic3d) [reply http/codegen/server.go]: Thank you for the feedback! In my opinion, trading a the simple declaration `var err error` for a if statement makes it less readable. But I'm fine with both of course, tell me which one you'd like to see in the PR ;)

Comment (raphael) [reply http/codegen/server.go]: You're right that simply declaring the error variable makes the Goa code easier to read but it also ends up generating Go code that isn't idiomatic:
```go
var err error
payload, err = decodeRequest(r)
```
While certainly not perfect one of the design goals of the Goa code generators has been to generate idiomatic code so I would tend to favor adding the `if`. Thank you!

Comment (cubic3d) [reply http/codegen/server.go]: I'll do ;)

**Comment by cubic3d** [comment]
Should be all fine now

**Comment by raphael** [comment]
Great! thank you, could you backport this to v2 as well please?

**Comment by cubic3d** [comment]
@raphael Sure, but looks like v2 does not pass builds at the moment
