### PR TITLE
Fix cyclic definition for CollectionOf

### LINKED ISSUE #2514: How to define a ResultType for Cycle struct?
# My first time try code 
### My DSL

```
var CategoryResult = ResultType("application/vnd.category", func() {
	Description("category")
	Attributes(func() {
		Field(1, "id", Int, "ID")
		Field(2, "p_category_id", Int, "p_category_id")
		Field(3, "children_category", CollectionOf("application/vnd.category"), "children_category")
		Field(4, "name", String, "name")
	})

	View("default", func() {
		Field(1, "id")
		Field(2, "p_category_id")
		Field(3, "name")
	})

	View("full", func() {
		Field(1, "id")
		Field(2, "p_category_id")
		Field(3, "name")
	})
})
```
### The error info

```
invalid CollectionOf argument: not a result type and not a known result type identifier in attribute
```

# My second time try code

### My DSL

```
var CategoryResult = ResultType("application/vnd.category", func() {
	Description("category")
	Attributes(func() {
		Field(1, "id", Int, "ID")
		Field(2, "p_category_id", Int, "p_category_id")
		Field(3, "children_category", CollectionOf(CategoryResult), "children_category")
		Field(4, "name", String, "name")
	})

	View("default", func() {
		Field(1, "id")
		Field(2, "p_category_id")
		Field(3, "name")
	})

	View("full", func() {
		Field(1, "id")
		Field(2, "p_category_id")
		Field(3, "name")
	})
})
```
### The error info

```
 initialization loop:
        _resources.go:26:5: CategoryResult refers to
       _resources.go:28:13: glob..func39.1 refers to
        _resources.go:26:5: CategoryResult
```

# My question
How to define a struct like the follow code in goa by DSL ?

```
type Category  struct {
	ID int `json:"id"`
	PCategoryID int `json:"p_category_id"`
	ChildrenCategory []Category `json:"children_category"`
	Name string `json:"name"`
}
```

### PR DESCRIPTION
**Pull request by nitinmohan87**
Fixes #2514

### CODE REVIEW

File: dsl/result_type.go [hunk 1]
```diff
@@ -282,10 +261,22 @@ func CollectionOf(v interface{}, adsl ...func()) *expr.ResultTypeExpr {
...
 				if mt, ok := dt.(*expr.ResultTypeExpr); ok {
 					m = mt
 				}
+			} else {
+				// Check if a result type exists with the given identifier
+				id, typeName, err := mediaTypeToResultType(id)
+				if err != nil {
+					eval.ReportError("invalid result type identifier %#v in CollectionOf: %s", id, err)
+				}
+				if dt := expr.Root.UserType(typeName); dt != nil {
```
Comment (raphael) [inline dsl/result_type.go:272]: Is it ok to do the above is err is not nil? (we don't return in the test above).

Comment (nitinmohan87) [reply dsl/result_type.go:272]: Done

**Comment by raphael** [comment]
Looks great, thank you! Can you please port this back to v2 as well?
