### PR TITLE
Pass arguments to final generator

### LINKED ISSUE #934: goagen gen does not allow custom flags
When writing a custom Generator it might be nice to add extra command line arguments to the generator.
For example: 
`goagen gen -d <design> --pkg-path=<mygenerator> --custom-arg=notparsed`

In the current implementation it looks like cobra eats up the --custom-arg flag and tries to parse it.
This means that goagen with generate an error like: `Error: unknown flag: --custom-arg`

It would be nice if cobra ignored other flags, or if goagen could provide a way to add custom commandline args to a custom generator.

### PR DESCRIPTION
**Pull request by jsimonetti**
This change will allow arguments to goagen which are add after the '--' argument to be passed allong to the generator.

The generate command becomes goagen gen -d <design> --pkg-path=<generator> -- --custom-arg=value

Fixes #934

### CODE REVIEW

File: goagen/meta/generator_test.go [hunk 1]
```diff
@@ -270,4 +288,18 @@ func Generate() ([]string, error) {
...
+import "fmt"
+import "os"
+
+func Generate() ([]string, error) {
+	for _, arg := range os.Args {
+		if arg == "{{.}}" {
+			return nil, nil
+		}
+	}
+	return nil, fmt.Errorf("no flag --custom=arg found")
```
Comment (raphael) [inline goagen/meta/generator_test.go]: `--custom=arg` should probably be `{{.}}`

**Comment by raphael** [comment]
Thank you, the PR looks great. Left two nitpick comments, I'll merge once you address these.

**Comment by raphael** [comment]
Thank you! Do you think you could also make a PR against the v1 branch?
