### PR TITLE
Protect against request bodies with unreasonable length

### LINKED ISSUE #332: Protect against large request bodies
The following middleware is used by other web frameworks to protect against requests with unreasonable body length:
```go
// PayloadSizeMiddleware tries to read the request body and fails if the size is too big.
func PayloadSizeMiddleware(next http.Handler) http.Handler {
 maxSize := int64(conf.GetSizeInBytes(confMaxBodySize))
 return http.HandlerFunc(func(wrt http.ResponseWriter, req *http.Request) {
  body, err := ioutil.ReadAll(http.MaxBytesReader(wrt, req.Body, maxSize))
  if err != nil {
                    ....
               }
 })
}
```
This doesn't work as is with goa because of the way encoding works: the decoders are responsible for reading the request body. The middleware could reset the body reader or there could be an option to configure the decoders to do the body length check.

### PR DESCRIPTION
**Pull request by raphael**
Fix #332

### CODE REVIEW

File: service_test.go [hunk 1]
```diff
@@ -56,6 +56,39 @@ var _ = Describe("Service", func() {
...
+		JustBeforeEach(func() {
+			muxHandler(rw, req, nil)
+		})
+
+		AfterEach(func() {
+			goa.MaxRequestBodyLength = oldMax
+		})
+
+		It("prevents reading more bytes", func() {
+			Ω(string(rw.Body)).Should(Equal(`{"code":"invalid_encoding","status":400,"detail":"http: request body too large"}` + "\n"))
```
Comment (arangamani) [inline service_test.go]: Wouldn't `413` be the appropriate status code in this case?

**Comment by raphael** [comment]
Yes it probably would, good point! I'll change it.
