### PR TITLE
Fix type name when generating error type validation

### LINKED ISSUE #2080: goa v2 gRPC custom errors validate on server side using wrong type
The code generated for custom error validation on server side uses the wrong type (or the wrong type is code generated):
`$GOPATH/src/foo/design/api.go`
```
package design

import (
	. "goa.design/goa/dsl"
)

var _ = Service("Foo", func() {
	Method("foobar", func() {
		Result(Bar)
		Error("foobar_error", FooBarError)
		GRPC(func() {
			Response(CodeOK)
			Response("foobar_error", CodeFailedPrecondition)
		})
	})
})

var Bar = ResultType("application/vnd.foo.bar", func() {
	TypeName("Bar")
	Attributes(func() {
		Field(1, "name", String)
		Required("name")
	})
	View("default", func() {
		Attribute("name")
	})
})

var FooBarError = ResultType("application/vnd.foo.foobar_error", func() {
	TypeName("FooBarError")

	Attributes(func() {
		Field(1, "details")
		Field(2, "id", String)
		Field(3, "name", String, func() {
			Meta("struct:error:name")
			Enum("foobar_error")
		})
		Required("details", "id", "name")
	})
})
```
The generated code does not compile:
```
$ goa gen foo/design
gen/foo/client.go
gen/foo/endpoints.go
gen/foo/service.go
gen/foo/views/view.go
gen/grpc/cli/foo/cli.go
gen/grpc/foo/client/cli.go
gen/grpc/foo/client/client.go
gen/grpc/foo/client/encode_decode.go
gen/grpc/foo/client/types.go
gen/grpc/foo/pb/foo.proto
gen/grpc/foo/server/encode_decode.go
gen/grpc/foo/server/server.go
gen/grpc/foo/server/types.go
$
$ go build foo/gen/grpc/foo/server
# foo/gen/grpc/foo/server
gen/grpc/foo/server/types.go:40:35: undefined: foopb.FooBarError
```
The generated `foo/gen/grpc/foo/server/types.go` file is using the wrong type for validation (or else the type name was generated incorrectly):
```
// Code generated by goa v2.0.0-wip, DO NOT EDIT.
//
// Foo gRPC server types
//
// Command:
// $ goa gen foo/design

package server

import (
	foo "foo/gen/foo"
	fooviews "foo/gen/foo/views"
	foopb "foo/gen/grpc/foo/pb"

	goa "goa.design/goa"
)

// NewFoobarResponse builds the gRPC response type from the result of the
// "foobar" endpoint of the "Foo" service.
func NewFoobarResponse(result *fooviews.BarView) *foopb.FoobarResponse {
	message := &foopb.FoobarResponse{}
	if result.Name != nil {
		message.Name = *result.Name
	}
	return message
}

// NewFoobarFoobarErrorError builds the gRPC error response type from the error
// of the "foobar" endpoint of the "Foo" service.
func NewFoobarFoobarErrorError(er *foo.FooBarError) *foopb.FoobarFoobarErrorError {
	message := &foopb.FoobarFoobarErrorError{
		Details: er.Details,
		Id:      er.ID,
		Name:    er.Name,
	}
	return message
}

// ValidateFooBarError runs the validations defined on FooBarError.
func ValidateFooBarError(message *foopb.FooBarError) (err error) {
        ^^^ message type should be *foopb.FoobarFoobarErrorError or else
        ^^^ the type name should have been generated as foopb.FooBarError,
        ^^^ which sounds better.
	if !(message.Name == "foobar_error") {
		err = goa.MergeErrors(err, goa.InvalidEnumValueError("message.name", message.Name, []interface{}{"foobar_error"}))
	}
	return
}
```

### PR DESCRIPTION
**Pull request by nitinmohan87**
Fixes #2080

### CODE REVIEW

File: grpc/codegen/service_data.go [hunk 1]
```diff
@@ -246,6 +246,10 @@ type (
 		SrcName string
 		// SrcRef is the fully qualified reference to the type being validated.
 		SrcRef string
+		// Kind indicates that the validation is for request (server-side),
+		// response (client-side), or both (server and client side) messages.
+		// It is used to generate validation code in the server and client packages.
+		Kind string
```
Comment (raphael) [inline grpc/codegen/service_data.go]: should this be a enum instead?

Comment (nitinmohan87) [reply grpc/codegen/service_data.go]: I can make it an enum..
